server:
  port: 8081

spring:
  cloud:
    config:
      server:

        git:
          uri: https://github.com/Y4NGWoo/Webstagram
          default-label: main

#  yml ??? ??? github repository? ??????
#  yml ??? ??? github repository? public ??? ?????
#  main ??? @EnableConfigServer ?????? ????

# actuator ??
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true